update bash scripts to use mainlib.guess_conf() instead of hardcoded values

diff --git a/bin/debsources-main b/bin/debsources-main
--- a/bin/debsources-main
+++ b/bin/debsources-main
@@ -20,19 +20,18 @@
 # Driver for update runs, both synchronous (e.g. cmdline) and asynchronous
 # (e.g. cron and pushes)
 
-# will be overridden by config.local.ini in the same dir, if present
-CONFFILE="/srv/debsources/etc/config.ini"
+conffile=`python -c 'from debsources import mainlib; print(mainlib.guess_conffile())'`
+if [ $? -ne 0 ]
+then
+    echo "Configuration file not found, aborting."
+    exit 2
+fi
 
 # -----------------------------------------------------------------------
 
 umask 0002
 export LANG=C
 
-alt_conffile=$(echo "$CONFFILE" | sed 's/config.ini/config.local.ini/')
-conffile="$CONFFILE"
-if [ -f "$alt_conffile" ] ; then
-    conffile="$alt_conffile"
-fi
 root_dir=$(grep "^root_dir:" "$conffile" | awk '{ print $2 }')
 conf_get () {
     local key="$1"
