add support to run hooks during debsources updates
currently supported hooks:
- add-package: a new version of a package has just been extracted
- rm-package: an old package version is about to be removed

diff --git a/bin/extract-all b/bin/extract-all
--- a/bin/extract-all
+++ b/bin/extract-all
@@ -40,18 +40,27 @@ extract_sources() {
     local sources_count=$(wc -l $srclist | cut -f 1 -d' ')
     stats_init "extract" "$sources_count"
     cat $srclist | \
-	while read package version _area dsc dest ; do
-	    stats_tick
-	    flags=""
-	    if [ "$verbose" = "0" ] ; then
-		flags="$flags --quiet"
-	    fi
-	    if [ "$dsc" = "NONE" ] ; then
+    while read package version _area dsc dest ; do
+	stats_tick
+	flags=""
+	if [ "$verbose" = "0" ] ; then
+	    flags="$flags --quiet"
+	fi
+	if [ "$dsc" = "NONE" ] ; then
+	    continue
+	fi
+	donefile="${dest}.done"	# e.g.: "/srv/debsources/sources/main/z/zodb/1:3.9.7-2.done"
+	if ! [ -f "$donefile" ] ; then
+	    if ! ${bindir}/extract-source $flags "$package" "$version" "$dsc" "$dest" ; then
+		warn "failed to extract ${package}/${version}"
 		continue
 	    fi
-	    if ! $bindir/extract-source $flags "$package" "$version" "$dsc" "$dest" ; then
-		warn "failed to extract package '$package' '$version'"
+	    if ! ${bindir}/visit-package add-package "$dest" "$package" "$version" ; then
+		warn "failed to visit ${package}/${version}"
+		continue
 	    fi
+	    touch "$donefile"
+	fi
     done
 }
 
diff --git a/bin/gc b/bin/gc
--- a/bin/gc
+++ b/bin/gc
@@ -38,31 +38,34 @@ if [ -z "$srclist" -o ! -f "$srclist" ] ; then
 fi
 
 garbage_collect() {
-    stats_init "gc" ""
     # ASSUMPTION: pool structure $root/sources/{main,contrib,non-free,...}/HASH/PACKAGE
     # e.g. /srv/debsources/sources/main/d/dotclear
     #      /srv/debsources/sources/main/libg/libglade2
-    find "$sources_dir" -mindepth 3 -maxdepth 3 -type d | \
-    while read pkgdir ; do
+    list_tmp=$(mktemp --tmpdir debsources.XXXXXXXXXX)
+    trap "rm -f $list_tmp" EXIT
+    find "$sources_dir" -mindepth 4 -maxdepth 4 -type d > $list_tmp
+    local list_len=$(wc -l $list_tmp | cut -f 1 -d' ')
+
+    stats_init "gc" "$list_len"
+    cat $list_tmp | \
+    while read versiondir ; do
 	stats_tick
-	local pkg=$(basename "$pkgdir")
-	if ! grep -q "^${pkg}[[:blank:]]" "$srclist" ; then
-	    # completely remove disappeared package
-	    info "gc: rm ${pkg}"
+	package=$(basename $(dirname $versiondir))
+	version=$(basename $versiondir)
+	if ! grep -q "^${package}[[:blank:]]${version}[[:blank:]]" "$srclist" ; then
+	    info "gc: rm ${package} ${version}"
 	    if [ "$dry_run" != "yes" ] ; then
-		rm -rf "$pkgdir"
-	    fi
-	else
-	    find "$pkgdir" -mindepth 1 -maxdepth 1 -type d | \
-	    while read versiondir ; do
-		local version=$(basename "$versiondir")
-		if ! grep -q "^${pkg}[[:blank:]]${version}[[:blank:]]" "$srclist" ; then
-		    info "gc: rm ${pkg} ${version}"
-		    if [ "$dry_run" != "yes" ] ; then
-			rm -rf "$versiondir" "${versiondir}.log" "${versiondir}.done" "${versiondir}.stats"
-		    fi
+		if ! ${bindir}/visit-package rm-package "$versiondir" "$package" "$version" ; then
+		    warn "failed to visit ${package}/${version}"
+		    continue
 		fi
-	    done
+		if ! rm -rf "$versiondir" "${versiondir}.log" "${versiondir}.stats" ; then
+		    warn "failed to remove ${package}/${version}"
+		    continue
+		fi
+		rmdir -p $(dirname $versiondir) 2> /dev/null || true
+		rm -f "${versiondir}.done"
+	    fi
 	fi
     done
 }
